services:
  php:
    image: php:8.1.3-apache
    container_name: symfony-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html        # zmienione z ./portfolio
    depends_on:
      - database
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    working_dir: /var/www/html
    command: >
      bash -c "apt-get update &&
               apt-get install -y git unzip zip libpq-dev libzip-dev libxml2-dev libonig-dev libcurl4-openssl-dev &&
               docker-php-ext-install pdo pdo_pgsql zip intl opcache &&
               apache2-foreground"

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
